---
- hosts: nfs-servers
  remote_user: root
  roles:
    - role: nfs-server

- hosts: nfs-servers-iptables
  remote_user: root
  roles:
    - role: nfs-server-iptables

- hosts: nfs-servers-firewalld
  remote_user: root
  roles:
    - role: nfs-server-firewalld
