---

nfs_server_packages:
  - libselinux-python
  - nfs-utils
  - rpcbind

nfs_server_services:
  - rpcbind
  - nfs
  - nfslock

nfs_server_config_settings:
  - { file: '/etc/sysconfig/nfs', key: 'MOUNTD_PORT', value: 892 }
  - { file: '/etc/sysconfig/nfs', key: 'STATD_PORT', value: 662 }
  - { file: '/etc/sysconfig/nfs', key: 'LOCKD_TCPPORT', value: 32803 }
  - { file: '/etc/sysconfig/nfs', key: 'LOCKD_UDPPORT', value: 32769 }

